{{- $name := "api" -}}
apiVersion: v1
kind: Workload
metadata:
  labels:
    app: {{ $name }}
  name: {{ $name }}
spec:
  type: ClusterIP
  ports:
  - name: "api"
    port: 80
    targetPort: 80
  selector:
    app: {{ $name }}
status:
  loadBalancer: {}
