{{- $name := "api" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $name }}
  name: {{ $name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ $name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - args:
        - --ini
        - app.ini
        image: lukadb/facialreconstruction:3.0
        name: {{ $name }}
        resources: {}
        ports:
          - containerPort: 80
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $name }}
  name: {{ $name }}
spec:
  ports:
  - name: "api"
    port: 80
    targetPort: 80
  selector:
    app: {{ $name }}
status:
  loadBalancer: {}

